# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vu3S1azwT13qYj4Si3RpXdqj8Asxsnl7

#Movie Recommendation System

#
**Recommender System** is a system that seeks to predict or filter preferences according to the user's choices. Recommender systems are utilized in a variety of areas including movies, music, news, books, research articles, search queries, social tags, and products in general. Recommender systems produce a list of recommendations in any of the two ways -

**Collaborative filtering**: Collaborative filtering approaches build a model from the user's past behavior (i.e. items purchased or searched by the user) as well as similar decisions made by other users. This model is then used to predict items (or ratings for items) that users may have an interest in
.
**Content-based filtering:** Content-based filtering approaches uses a series of discrete characteristics of an item in order to recommend additional items with similar properties. Content-based filtering methods are totally based on a description of the item and a profile of the user's preferences. It recommends items based on the user's past preferences. Let's develop a basic recommendation system using Python and Pandas.

Let's develop a basic recommendation system by suggesting items that are most similar to a particular item, in this case, movies. It just tells what movies/items are most similar to the user's movie choice.

#Import Library
"""

import pandas as pd

import numpy as np

"""#Import Dataset"""

df = pd.read_csv(r'https://raw.githubusercontent.com/YBI-Foundation/Dataset/main/Movies%20Recommendation.csv')

df.head()

df.info()

df.shape

df.columns

"""#Get Feature Selection"""

df_features = df[['Movie_Genre', 'Movie_Keywords', 'Movie_Tagline', 'Movie_Cast', 'Movie_Director']].fillna('')

"""#Selected five existing features to recommend movies. It may vary from one project to another. Like one can add vote counts, budget, language,etc."""

df_features.shape

df_features

X =df_features['Movie_Genre'] +''+ df_features['Movie_Keywords'] +''+df_features['Movie_Tagline']+''+ df_features['Movie_Cast'] +''+ df_features['Movie_Director']

X.shape

"""#Get Feature Text Conversion To Tokens"""

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()

X= tfidf.fit_transform(X)

X.shape

print(X)

"""#Get Similarity Score Using Consine Similarity"""

from sklearn.metrics.pairwise import cosine_similarity

Similarity_Score=cosine_similarity(X)

Similarity_Score

Similarity_Score.shape

"""#Get Movie Name As Input From User And Validate For Closest Spelling"""

Favourite_Movie_Name = input(' Enter your favourite movie name : ')

All_Movies_Title_List = df['Movie_Title'].tolist()

import difflib

Movie_Recommendation = difflib.get_close_matches (Favourite_Movie_Name, All_Movies_Title_List)
print (Movie_Recommendation)

Close_match = Movie_Recommendation[0]
print(Close_match)

Index_of_Close_Match_Movie = df[df.Movie_Title == Close_match]['Movie_ID'].values[0]

Recommendation_Score = list(enumerate(Similarity_Score[Index_of_Close_Match_Movie]))
print(Recommendation_Score)

len(Recommendation_Score)

"""#Get All Movies Sort Based on Recommendation Score wrt Favour"""

Sorted_Similar_Movies = sorted(Recommendation_Score, key = lambda x:x[1], reverse=True)
print(Sorted_Similar_Movies)

print('Top 30 Movies Suggested for You: \n')
i=1
for movie in Sorted_Similar_Movies:
  index = movie[0]
  title_from_index=df[df.index==index]['Movie_Title'].values[0]
  if (i<31):
    print(i, '.',title_from_index)
    i+=1

"""#Top 10 Movie Recommendation System"""

Movie_Name = input('Enter your favourite movie name : ')
list_of_all_titles=df['Movie_Title'].tolist()
Find_Close_Match = difflib.get_close_matches(Movie_Name, list_of_all_titles)
Close_Match = Find_Close_Match[0]
Index_of_Movie=df[df.Movie_Title == Close_Match]['Movie_ID'].values[0]
Recommendation_Score = list(enumerate(Similarity_Score [Index_of_Movie]))
sorted_similar_movies = sorted(Recommendation_Score, key = lambda x:x[1], reverse=True)
print("Top 10 Movies suggested for you: \n")
i=1
for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index=df[df.Movie_ID==index]['Movie_Title'].values
  if (i<11):
    print(i,'.',title_from_index)
    i+=1